[package]
name = "fhrs"
version = "0.1.0"
edition = "2024"

[lib]
name = "fhrs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
ndarray = { version = "0.16", features = ["rayon"] }
numpy = "0.27"
pyo3 = { version = "0.27", features = ["anyhow"] }
rayon = "1.11"
